// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.InteropServices

[<assembly: AssemblyTitleAttribute("Server")>]
[<assembly: AssemblyProductAttribute("Alan Framework")>]
[<assembly: GuidAttribute("E95E7A2F-20A3-4C0A-9C7A-A4644AFB35AA")>]
[<assembly: AssemblyCompanyAttribute("Enkomio")>]
[<assembly: AssemblyDescriptionAttribute("A post-exploitation framework.")>]
[<assembly: AssemblyVersionAttribute("7.0.514.10")>]
[<assembly: AssemblyFileVersionAttribute("7.0.514.10")>]
[<assembly: AssemblyInformationalVersionAttribute("7.0.514.10")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Server"
    let [<Literal>] AssemblyProduct = "Alan Framework"
    let [<Literal>] Guid = "E95E7A2F-20A3-4C0A-9C7A-A4644AFB35AA"
    let [<Literal>] AssemblyCompany = "Enkomio"
    let [<Literal>] AssemblyDescription = "A post-exploitation framework."
    let [<Literal>] AssemblyVersion = "7.0.514.10"
    let [<Literal>] AssemblyFileVersion = "7.0.514.10"
    let [<Literal>] AssemblyInformationalVersion = "7.0.514.10"
